{
  "type": "record",
  "name": "StockReserved",
  "namespace": "OrderFlow.Contracts",
  "fields": [
    { "name": "EventId", "type": { "type": "string", "logicalType": "uuid" } },
    { "name": "EventName", "type": "string" },
    { "name": "CustomerId", "type": "string" },
    { "name": "OrderId", "type": "string" },
    {
      "name": "OccurredAt",
      "type": { "type": "long", "logicalType": "timestamp-millis" }
    },
    { "name": "EventVersion", "type": "int" },
    { "name": "CorrelationId", "type": "string" },
    { "name": "CausationId", "type": "string" },
    { "name": "ReservationStatus", "type": "string" }
  ]
}
